### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by edgingtonn1** [alberto-p/kpax2#1]
I'm having a problem installing kpax2 with R version 3.3.0 (2016-05-03) -- "Supposedly Educational" & OS X 'El Capitan'. Below is the error:

`install.packages("kpax2_1.0.0.zip", repos=NULL, type="source")
Installing package into ‘~/Library/R/3.3/library’
(as ‘lib’ is unspecified)
Error in rawToChar(block[seq_len(ns)]) : 
  embedded nul in string: 'PK\003\004\n\0\0\0\0\0\xf6\xa4\x8eHϒ\xccrms\0\0ms\0\0\022\0\0\0kpax2_1.0.0.tar.gz\037\x8b\b\0\0\0\0\0\0\006\xed}iw\xdbF\xb2h>\xeb\034\xff\a\x98NFDL\xd1$%\xdbwtC\xcfS\xbcĞx{\x96<N\xa2hr@\022\x92`'
Warning message:
In install.packages("kpax2_1.0.0.zip", repos = NULL, type = "source") :
  installation of package ‘kpax2_1.0.0.zip’ had non-zero exit status`

**Comment by albertopessia** [comment]
I rebuilt the package with R 3.3.0 and I was able to install it without problems on Win7, Win10 and Ubuntu 16.04. Unfortunately, I don't have access to a Mac and I can't reproduce the bug.

Would you be so kind to try again with this newest version? You can download it from http://www.helsinki.fi/bsg/software/kpax2/

If it still does not work, we will start digging further into the problem.

**Comment by edgingtonn1** [comment]
Thanks for looking into this. I tried again with the new version (kpax2_1.0.1), and I still get a similar error on R version 3.3.0 (with MacOSX 'El Capitan').  
`Error in rawToChar(block[seq_len(ns)]) : 
  embedded nul in string: 'PK\003\004\024\0\0\0\b\0\xd7;\xb8H\xef\xc3z\xb6}\0\0\0\x94\0\0\0\n\0\0\0HISTORY.md=\xceK\n\xc20\024F\xe1yV\xf1Cg\016BjW\020\xa4\x82\x88E\xea\nRs\x8b\027\xf2(\xc9\025]\xbe-B\027p>N\x83\xeb\xe2\xbeG\x8c\024\xc8U\u0090\x85\xaaRM\x83V\033\xdd'`

It installed just fine on Ubuntu 14 LTS (64-bit IntelCore i7-4700MQ), but not on a Ubuntu 12 LTS VM (Virtualbox 5.0.20 r106931) running on MacOSX 'El Capitan' (exiting with the same error type):
`Error in rawToChar(block[seq_len(ns)]) : 
  embedded nul in string: 'PK\003\004\024\0\0\0\b\0\xd7;\xb8H\xef\xc3z\xb6}\0\0\0\x94\0\0\0\n\0\0\0HISTORY.md=\xceK\n\xc20\024F\xe1yV\xf1Cg\016BjW\020\xa4\x82\x88E\xea\nRs\x8b\027\xf2(\xc9\025]\xbe-B\027p>N\x83\xeb\xe2\xbeG\x8c\024\xc8U\u0090\x85\xaaRM\x83V\033\xdd'

**Comment by edgingtonn1** [comment]
OK, as long as kpax2 is installed within R using the devtools package's "install_github()" command, all is well on several different OS's and R versions. It might be helpful for others to add these commands below in your [README.md](https://github.com/alberto-p/kpax2/blob/master/README.md) file _(esp. for Mac Users)._
Cheers!

`require(devtools)`
`install_github("alberto-p/kpax2/kpax2")`
